services:
  - type: web
    name: glory-furniture-hub
    runtime: docker
    plan: free
    region: singapore
    dockerfilePath: ./Dockerfile
    envVars:
      - key: PORT
        value: 10000
      - key: DEBUG
        value: "False"
      - key: SECRET_KEY
        generateValue: true
