# Generated by Django 6.1.1 on 2026-09-20 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='installment_days',
            field=models.PositiveIntegerField(default=30, help_text='Total days for product completion and 3-installment payment schedule.'),
        ),
    ]
