# Generated by Django 6.1.1 on 2026-09-20 16:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_product_installment_days'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products', to='store.category'),
        ),
        migrations.AlterField(
            model_name='product',
            name='installment_days',
            field=models.PositiveIntegerField(default=60, help_text='Total days for product completion and 3-installment payment schedule.'),
        ),
    ]
