# Generated by Django 6.1.1 on 2026-09-19 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='WebsiteSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('website_name', models.CharField(default='Glory Furniture Hub', max_length=150)),
                ('tagline', models.CharField(blank=True, default='Fine Teak Craftsmanship', max_length=255)),
                ('primary_email', models.EmailField(blank=True, default='support@gloryfurniture.com', max_length=254)),
                ('secondary_email', models.EmailField(blank=True, default='', max_length=254)),
                ('phone', models.CharField(blank=True, default='', max_length=30)),
                ('whatsapp_number', models.CharField(blank=True, default='', max_length=30)),
                ('address', models.TextField(blank=True, default='')),
                ('city', models.CharField(blank=True, default='', max_length=100)),
                ('state', models.CharField(blank=True, default='', max_length=100)),
                ('pincode', models.CharField(blank=True, default='', max_length=20)),
                ('country', models.CharField(blank=True, default='India', max_length=100)),
                ('footer_description', models.TextField(blank=True, default='Generations of master carpentry in Hyderabad. Specializing in seasoned solid Burma teakwood, pure mortise-and-tenon joints, and custom architectural furniture for discerning Indian homes.')),
                ('copyright_text', models.CharField(blank=True, default='© 2026 Glory Furniture Hub. Handcrafted in Hyderabad, India.', max_length=255)),
                ('facebook_url', models.URLField(blank=True, default='', max_length=500)),
                ('instagram_url', models.URLField(blank=True, default='', max_length=500)),
                ('youtube_url', models.URLField(blank=True, default='', max_length=500)),
                ('twitter_url', models.URLField(blank=True, default='', max_length=500)),
                ('linkedin_url', models.URLField(blank=True, default='', max_length=500)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Website Settings',
                'verbose_name_plural': 'Website Settings',
            },
        ),
    ]
