# Generated by Django 6.1.1 on 2026-10-02 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PageCMSContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('welcome_bg_image', models.ImageField(blank=True, null=True, upload_to='cms/')),
                ('welcome_bg_image_url', models.URLField(blank=True, default='', max_length=1000)),
                ('welcome_eyebrow', models.CharField(default='WELCOME TO', max_length=200)),
                ('welcome_title_main', models.CharField(default='Glory', max_length=200)),
                ('welcome_title_highlight', models.CharField(default='Furniture Hub', max_length=200)),
                ('welcome_cta_text', models.CharField(default='Get Started', max_length=100)),
                ('welcome_badge1_title', models.CharField(default='Modern Designs', max_length=100)),
                ('welcome_badge2_title', models.CharField(default='Trusted Quality', max_length=100)),
                ('welcome_badge3_title', models.CharField(default='Safe Delivery', max_length=100)),
                ('login_slide1_image', models.ImageField(blank=True, null=True, upload_to='cms/')),
                ('login_slide1_image_url', models.URLField(blank=True, default='https://lh3.googleusercontent.com/aida/AEtjO1W7s1H6HLs_yNUpBwueaww35O5laxZ5AP0g7J4UDx4PHugVL5djKq-6BULWAG0WACZVA_huQ30HTSZINIOYoXeUwv-vTvFI-OULSFOFIBxSqjHg01I_ZmMfUGn0M8Og8BEvvW1yl0FzNDCUAiXmGcMILvDIbiZG10Nroh1KxEUNmS7Z71xLaDx9Fy37E0NjS7-bcT7FwY2CKrYaGrzISS6LpZ1QsJdvaE2TjT0XuE0Pu-74fdaNCZDKzhg', max_length=1000)),
                ('login_slide2_image_url', models.URLField(blank=True, default='https://lh3.googleusercontent.com/aida/AEtjO1Uxw6WL1UygfI-XYJNyq47ksbYE4c4u6ptdffKKojNqw14sDVM1BszDEAC6Dr98oRXU4BngcLjDilAn9HU6OKg0wNQfrtDjEcBi8EJ_BHRWtw2SAtqmKb_OJQO2pqzYFflUFSsAPxzSba74X5Sm0C1_saragShT6aPlFbymQTSOp308wUoPfkiFYh3Y-WgpOgYq7jrZsNvfBVU8i2Gp9_WOs6Vdc_HBYXpmCKX-JalLdyOUi-2ibdLdlAg', max_length=1000)),
                ('login_slide3_image_url', models.URLField(blank=True, default='https://lh3.googleusercontent.com/aida/AEtjO1XQpLWAVX5fET2usaL2iEHeOkAwyq287h2Obq9elLp8XTDq7E86i8apiUE1xd5fLRiHX2u_uaAuodl1WZVOKfdHxt8DdbIY0OSszt664oT5I2gfvapwMT0NhvzyiygqhuxnVXSxTzOfLil2R24wbSA4vB7SGpTsBHfsYhrevVGC4Sih2ZFSmja83k5LfnA7W4GWTinFgkDZZpVwT1XOxnBVb21uH5fXBWVONvqhw7OJbyXZ8HyDdL6N3v8', max_length=1000)),
                ('login_hero_title', models.CharField(default='Welcome Back', max_length=200)),
                ('login_hero_highlight', models.CharField(default='Glory Furniture Hub', max_length=200)),
                ('login_card_subtitle', models.CharField(default='CLIENT AUTHENTICATION', max_length=200)),
                ('login_card_title', models.CharField(default='Welcome Back', max_length=200)),
                ('login_card_description', models.TextField(default='Sign in to track orders, consultation bookings, and saved blueprints')),
                ('login_badge1_title', models.CharField(default='Order Tracking', max_length=150)),
                ('login_badge1_desc', models.CharField(default='Live kiln, joinery & white-glove transport tracking.', max_length=255)),
                ('login_badge2_title', models.CharField(default='Blueprint Vault', max_length=150)),
                ('login_badge2_desc', models.CharField(default='Architect CAD specifications and custom timber grains.', max_length=255)),
                ('login_badge3_title', models.CharField(default='Collector Privileges', max_length=150)),
                ('login_badge3_desc', models.CharField(default='Reserved kiln batches & master woodworker sessions.', max_length=255)),
                ('register_slide1_image', models.ImageField(blank=True, null=True, upload_to='cms/')),
                ('register_slide1_image_url', models.URLField(blank=True, default='https://lh3.googleusercontent.com/aida/AEtjO1W7s1H6HLs_yNUpBwueaww35O5laxZ5AP0g7J4UDx4PHugVL5djKq-6BULWAG0WACZVA_huQ30HTSZINIOYoXeUwv-vTvFI-OULSFOFIBxSqjHg01I_ZmMfUGn0M8Og8BEvvW1yl0FzNDCUAiXmGcMILvDIbiZG10Nroh1KxEUNmS7Z71xLaDx9Fy37E0NjS7-bcT7FwY2CKrYaGrzISS6LpZ1QsJdvaE2TjT0XuE0Pu-74fdaNCZDKzhg', max_length=1000)),
                ('register_slide2_image_url', models.URLField(blank=True, default='https://lh3.googleusercontent.com/aida/AEtjO1Uxw6WL1UygfI-XYJNyq47ksbYE4c4u6ptdffKKojNqw14sDVM1BszDEAC6Dr98oRXU4BngcLjDilAn9HU6OKg0wNQfrtDjEcBi8EJ_BHRWtw2SAtqmKb_OJQO2pqzYFflUFSsAPxzSba74X5Sm0C1_saragShT6aPlFbymQTSOp308wUoPfkiFYh3Y-WgpOgYq7jrZsNvfBVU8i2Gp9_WOs6Vdc_HBYXpmCKX-JalLdyOUi-2ibdLdlAg', max_length=1000)),
                ('register_slide3_image_url', models.URLField(blank=True, default='https://lh3.googleusercontent.com/aida/AEtjO1XQpLWAVX5fET2usaL2iEHeOkAwyq287h2Obq9elLp8XTDq7E86i8apiUE1xd5fLRiHX2u_uaAuodl1WZVOKfdHxt8DdbIY0OSszt664oT5I2gfvapwMT0NhvzyiygqhuxnVXSxTzOfLil2R24wbSA4vB7SGpTsBHfsYhrevVGC4Sih2ZFSmja83k5LfnA7W4GWTinFgkDZZpVwT1XOxnBVb21uH5fXBWVONvqhw7OJbyXZ8HyDdL6N3v8', max_length=1000)),
                ('register_hero_badge', models.CharField(default='BURMA TEAK MINIMALIST BED', max_length=200)),
                ('register_hero_title', models.CharField(default='Glory Furniture Hub', max_length=200)),
                ('register_hero_desc', models.TextField(default='Experience timeless Burma teak mastery shaped with precision joinery and sustainable heritage craft')),
                ('register_card_subtitle', models.CharField(default='HAND-CRAFTED SOLID BURMA TEAK', max_length=200)),
                ('register_card_title', models.CharField(default='Create Customer Account', max_length=200)),
                ('register_card_description', models.TextField(default='Access exclusive handcrafted solid teak collections & custom orders')),
                ('register_badge1_title', models.CharField(default='Sign up account', max_length=150)),
                ('register_badge1_desc', models.CharField(default='Basic credentials & authentication.', max_length=255)),
                ('register_badge2_title', models.CharField(default='Bespoke preferences', max_length=150)),
                ('register_badge2_desc', models.CharField(default='Wood grains, finish & dimensions.', max_length=255)),
                ('register_badge3_title', models.CharField(default='VIP catalog access', max_length=150)),
                ('register_badge3_desc', models.CharField(default='Private studio consults & pricing.', max_length=255)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Page CMS Content',
                'verbose_name_plural': 'Page CMS Content',
            },
        ),
    ]
