# Generated by Django 6.1.1 on 2026-10-10 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_pagecmscontent'),
    ]

    operations = [
        migrations.CreateModel(
            name='HomeMediaCMS',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hero_card_1_image', models.ImageField(blank=True, null=True, upload_to='cms/')),
                ('hero_card_1_url', models.URLField(blank=True, default='/static/images/hero_card_living_clean.jpg', max_length=1000)),
                ('hero_card_1_title', models.CharField(default='The Living Edit', max_length=200)),
                ('hero_card_1_subtitle', models.CharField(default='Warm, timeless essentials', max_length=255)),
                ('hero_card_2_image', models.ImageField(blank=True, null=True, upload_to='cms/')),
                ('hero_card_2_url', models.URLField(blank=True, default='/static/images/hero_card_bed_full.jpg', max_length=1000)),
                ('hero_card_2_title', models.CharField(default='Soft Retreats', max_length=200)),
                ('hero_card_2_subtitle', models.CharField(default='Rest in natural comfort', max_length=255)),
                ('hero_card_3_image', models.ImageField(blank=True, null=True, upload_to='cms/')),
                ('hero_card_3_url', models.URLField(blank=True, default='/static/images/hero_card_dining_full.jpg', max_length=1000)),
                ('hero_card_3_title', models.CharField(default='Gather & Dine', max_length=200)),
                ('hero_card_3_subtitle', models.CharField(default='Spaces for meaningful moments', max_length=255)),
                ('hero_card_4_image', models.ImageField(blank=True, null=True, upload_to='cms/')),
                ('hero_card_4_url', models.URLField(blank=True, default='https://lh3.googleusercontent.com/aida-public/AB6AXuBP6Sc2G1ga1CiPRkIPjlFaE4nLFkuJKMJufcJ3XraTvuqM70_TjdbaX8DqUYVLYrbmH0bdrorwT6ULYwBOMmsfEuxDN2bqvx5wd72KCTjWKKh1XJSFqLVOMTEvNJTGmwuYIHMqrRYmHhpV6dBbP5hVhEVg9PPIyzvgYJb-RBcwvZb1ZR7xelUEL26wh_OZzoxcaYT7s5lRoW5rq5sMFtjDaUehA94PJRn4LO8MVcFANFFBp_JrB-w', max_length=1000)),
                ('hero_card_4_title', models.CharField(default='Artisan Sanctuaries', max_length=200)),
                ('hero_card_4_subtitle', models.CharField(default='Bespoke handcrafted suites', max_length=255)),
                ('cat_beds_image', models.ImageField(blank=True, null=True, upload_to='cms/')),
                ('cat_beds_url', models.URLField(blank=True, default='/static/images/cat_beds.png', max_length=1000)),
                ('cat_sofa_image', models.ImageField(blank=True, null=True, upload_to='cms/')),
                ('cat_sofa_url', models.URLField(blank=True, default='/static/images/cat_sofa.png', max_length=1000)),
                ('cat_diwan_image', models.ImageField(blank=True, null=True, upload_to='cms/')),
                ('cat_diwan_url', models.URLField(blank=True, default='/static/images/cat_diwan.png', max_length=1000)),
                ('cat_dining_image', models.ImageField(blank=True, null=True, upload_to='cms/')),
                ('cat_dining_url', models.URLField(blank=True, default='/static/images/cat_dining.png', max_length=1000)),
                ('cat_dressing_image', models.ImageField(blank=True, null=True, upload_to='cms/')),
                ('cat_dressing_url', models.URLField(blank=True, default='/static/images/cat_dressing.png', max_length=1000)),
                ('cat_doors_image', models.ImageField(blank=True, null=True, upload_to='cms/')),
                ('cat_doors_url', models.URLField(blank=True, default='/static/images/cat_doors.png', max_length=1000)),
                ('cat_teapoy_image', models.ImageField(blank=True, null=True, upload_to='cms/')),
                ('cat_teapoy_url', models.URLField(blank=True, default='/static/images/cat_teapoy.png', max_length=1000)),
                ('cat_podiums_image', models.ImageField(blank=True, null=True, upload_to='cms/')),
                ('cat_podiums_url', models.URLField(blank=True, default='/static/images/cat_podiums.png', max_length=1000)),
                ('video_showcase_file', models.FileField(blank=True, null=True, upload_to='cms/videos/')),
                ('video_showcase_url', models.URLField(blank=True, default='/static/videos/product_1.mp4', max_length=1000)),
                ('video_tagline', models.CharField(default='Glory Atelier • Archival Series', max_length=200)),
                ('video_title', models.CharField(default='Chapter 04: Handcrafted Royal Teak Bedroom Collection', max_length=255)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Home Media CMS',
                'verbose_name_plural': 'Home Media CMS',
            },
        ),
    ]
