# Generated by Django 6.1.1 on 2026-10-10 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_homemediacms'),
    ]

    operations = [
        migrations.AddField(
            model_name='homemediacms',
            name='hero_card_5_image',
            field=models.ImageField(blank=True, null=True, upload_to='cms/'),
        ),
        migrations.AddField(
            model_name='homemediacms',
            name='hero_card_5_subtitle',
            field=models.CharField(default='Sculptural lounge aesthetic', max_length=255),
        ),
        migrations.AddField(
            model_name='homemediacms',
            name='hero_card_5_title',
            field=models.CharField(default='Nordic Bouclé Living', max_length=200),
        ),
        migrations.AddField(
            model_name='homemediacms',
            name='hero_card_5_url',
            field=models.URLField(blank=True, default='https://lh3.googleusercontent.com/aida-public/AB6AXuBfiW_WTyRCjiNePezPop4j9QGCOkz68YNMPRhRu1fMVWzgItVDsALH4pRnidHUjQgywuEHvNR8ze_1VGBrZrA3rn8ARj47fI5p6uVLmiWaOC6WIU9O-eqdVmb5EfJ2N7YH6WYOYm-el7G28elk70IzRIM26cpbpSVFSzPwblOUOCTKTUlGPVdNBGoXKrKvEcWbnVxIWL9d84y9tEiCdCNhBVHNvjAGIpMkBr6ckwIp_m-vvLIMAmA', max_length=1000),
        ),
        migrations.AddField(
            model_name='homemediacms',
            name='hero_card_6_image',
            field=models.ImageField(blank=True, null=True, upload_to='cms/'),
        ),
        migrations.AddField(
            model_name='homemediacms',
            name='hero_card_6_subtitle',
            field=models.CharField(default='Generational teak mastery', max_length=255),
        ),
        migrations.AddField(
            model_name='homemediacms',
            name='hero_card_6_title',
            field=models.CharField(default='Architectural Pavilion', max_length=200),
        ),
        migrations.AddField(
            model_name='homemediacms',
            name='hero_card_6_url',
            field=models.URLField(blank=True, default='https://lh3.googleusercontent.com/aida-public/AB6AXuAeX-7-m4xsZYUC1QI8Uul1nEoQ3G4b-o0GbQrVoGzRA1X56EcWlz-F5_KbtccY4AOAzW6RtFfqG-7VBfxqbnvfLXgiIgtKWgzDzBpa3Ix503c-nFY2APbz9Dkr-xxRAR_Sy4NwKzkvBr0-aUe4_bIOw3EALXmwSX7VmYGOzm8fX5_uF-WUF0Ame1zwakgBIZBlUOzuqpz3abxrpBxnffu2t4knM5FSJqDqUCUfjCrBCaDHT5hqUEM', max_length=1000),
        ),
    ]
