# Generated by Django 6.1.1 on 2026-09-15 14:36

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('bookings', '0003_order_installment_plan_snapshot_order_next_due_date_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='InstallmentPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='e.g. 2 Installments, 3 Monthly Payments, 6 Installments', max_length=100)),
                ('slug', models.SlugField(max_length=100, unique=True)),
                ('installment_count', models.PositiveSmallIntegerField(default=3, help_text='Number of payments')),
                ('percentages', models.JSONField(default=list, help_text='Optional percentage distribution e.g. [33.33, 33.33, 33.34]. If empty, split equally.')),
                ('interval_days', models.PositiveIntegerField(default=30, help_text='Days between each installment')),
                ('min_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Minimum order total required', max_digits=12)),
                ('max_amount', models.DecimalField(blank=True, decimal_places=2, help_text='Maximum order total allowed', max_digits=12, null=True)),
                ('is_active', models.BooleanField(default=True, help_text='Only active plans are displayed during checkout')),
                ('description', models.TextField(blank=True, default='', help_text='Short patron-facing explanation')),
                ('display_order', models.PositiveSmallIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Installment Plan',
                'verbose_name_plural': 'Installment Plans',
                'ordering': ['display_order', 'installment_count'],
            },
        ),
        migrations.CreateModel(
            name='WebhookEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_id', models.CharField(blank=True, db_index=True, default='', max_length=120)),
                ('event_type', models.CharField(blank=True, default='', max_length=100)),
                ('gateway_order_id', models.CharField(blank=True, db_index=True, default='', max_length=120)),
                ('gateway_payment_id', models.CharField(blank=True, default='', max_length=120)),
                ('payload_hash', models.CharField(db_index=True, help_text='SHA-256 hash of payload', max_length=64)),
                ('payload', models.JSONField(default=dict)),
                ('status', models.CharField(choices=[('RECEIVED', 'Received'), ('PROCESSED', 'Processed'), ('IGNORED', 'Ignored'), ('FAILED', 'Failed')], default='RECEIVED', max_length=30)),
                ('error_message', models.TextField(blank=True, default='')),
                ('received_at', models.DateTimeField(auto_now_add=True)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Cashfree Webhook Event',
                'verbose_name_plural': 'Cashfree Webhook Events',
                'ordering': ['-received_at'],
            },
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_id', models.CharField(blank=True, db_index=True, max_length=100, unique=True)),
                ('payment_type', models.CharField(choices=[('FULL', 'Full Payment'), ('INSTALLMENT', 'Installment Payment')], default='FULL', max_length=20)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('currency', models.CharField(default='INR', max_length=10)),
                ('gateway', models.CharField(default='Cashfree', max_length=50)),
                ('gateway_order_id', models.CharField(blank=True, db_index=True, default='', max_length=120)),
                ('gateway_payment_id', models.CharField(blank=True, db_index=True, default='', max_length=120)),
                ('payment_session_id', models.CharField(blank=True, default='', max_length=255)),
                ('payment_method', models.CharField(blank=True, default='UPI', max_length=50)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('PROCESSING', 'Processing'), ('PAID', 'Paid'), ('FAILED', 'Failed'), ('CANCELLED', 'Cancelled'), ('REFUNDED', 'Refunded')], db_index=True, default='PENDING', max_length=30)),
                ('gateway_response', models.JSONField(blank=True, default=dict)),
                ('failure_reason', models.TextField(blank=True, default='')),
                ('refund_status', models.CharField(blank=True, default='', max_length=30)),
                ('refund_id', models.CharField(blank=True, default='', max_length=100)),
                ('paid_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payments', to=settings.AUTH_USER_MODEL)),
                ('installment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payments', to='bookings.installment')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='bookings.order')),
            ],
            options={
                'verbose_name': 'Payment Transaction',
                'verbose_name_plural': 'Payment Transactions',
                'ordering': ['-created_at'],
            },
        ),
    ]
