# Generated by Django 6.1.1 on 2026-09-07 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('booking_id', models.CharField(blank=True, max_length=50, unique=True)),
                ('customer_name', models.CharField(max_length=150)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=25)),
                ('consultation_type', models.CharField(choices=[('Showroom Visit', 'Showroom Visit (Banjara Hills / Kukatpally)'), ('Video Consultation', 'Live Video Design Consultation'), ('In-Home Site Measurement', 'Master Artisan In-Home Measurement')], default='Showroom Visit', max_length=80)),
                ('preferred_date', models.DateField()),
                ('time_slot', models.CharField(default='10:00 AM - 11:30 AM', max_length=80)),
                ('wood_preference', models.CharField(default='Pure Grade-A Burma Teak', max_length=120)),
                ('address', models.TextField(blank=True, default='')),
                ('notes', models.TextField(blank=True, default='')),
                ('status', models.CharField(choices=[('Confirmed', 'Confirmed'), ('Scheduled', 'Scheduled'), ('In Review', 'In Review'), ('Completed', 'Completed'), ('Cancelled', 'Cancelled')], default='Confirmed', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
