# Generated by Django 6.1.1 on 2026-09-11 16:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0001_initial'),
        ('store', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Installment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('installment_number', models.PositiveSmallIntegerField()),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('due_date', models.DateField()),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('PROCESSING', 'Processing'), ('PAID', 'Paid'), ('FAILED', 'Failed'), ('OVERDUE', 'Overdue'), ('CANCELLED', 'Cancelled')], default='PENDING', max_length=30)),
                ('payment_id', models.CharField(blank=True, default='', max_length=100)),
                ('paid_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['installment_number'],
            },
        ),
        migrations.AlterField(
            model_name='booking',
            name='consultation_type',
            field=models.CharField(choices=[('Showroom Visit', 'Showroom Visit (Banjara Hills / Kukatpally)'), ('Video Consultation', 'Live Video Design Consultation'), ('In-Home Site Measurement', 'Master Artisan In-Home Measurement'), ('Product Order & In-Home Delivery', 'Product Order & In-Home Delivery')], default='Showroom Visit', max_length=80),
        ),
        migrations.AlterField(
            model_name='booking',
            name='status',
            field=models.CharField(choices=[('Confirmed', 'Confirmed'), ('Scheduled', 'Scheduled'), ('In Review', 'In Review'), ('Payment Pending', 'Payment Pending'), ('Completed', 'Completed'), ('Cancelled', 'Cancelled')], default='Confirmed', max_length=50),
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_number', models.CharField(blank=True, max_length=50, unique=True)),
                ('customer_name', models.CharField(max_length=150)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=25)),
                ('shipping_address', models.TextField(blank=True, default='')),
                ('product_name', models.CharField(max_length=250)),
                ('selected_size', models.CharField(default='Standard', max_length=100)),
                ('selected_wood', models.CharField(default='Pure Grade-A Burma Teak', max_length=120)),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('paid_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('remaining_amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('payment_plan', models.CharField(choices=[('FULL_PAYMENT', 'Full Payment'), ('THREE_INSTALLMENTS', 'Three Installments')], default='FULL_PAYMENT', max_length=30)),
                ('order_status', models.CharField(choices=[('PENDING_PAYMENT', 'Pending Payment'), ('PARTIALLY_PAID', 'Partially Paid'), ('FULLY_PAID', 'Fully Paid'), ('PROCESSING', 'Processing'), ('SHIPPED', 'Shipped'), ('DELIVERED', 'Delivered'), ('CANCELLED', 'Cancelled')], default='PENDING_PAYMENT', max_length=30)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('booking', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to='bookings.booking')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='store.product')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='InstallmentRescheduleAudit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('old_due_date', models.DateField()),
                ('new_due_date', models.DateField()),
                ('changed_by', models.CharField(default='Master Studio Admin', max_length=150)),
                ('reason', models.TextField()),
                ('customer_notified', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('installment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reschedule_audits', to='bookings.installment')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reschedule_audits', to='bookings.order')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='installment',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='installments', to='bookings.order'),
        ),
        migrations.CreateModel(
            name='PaymentTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gateway', models.CharField(default='Razorpay', max_length=50)),
                ('gateway_payment_id', models.CharField(blank=True, max_length=100, null=True, unique=True)),
                ('gateway_order_id', models.CharField(blank=True, default='', max_length=100)),
                ('gateway_signature', models.CharField(blank=True, default='', max_length=255)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('currency', models.CharField(default='INR', max_length=10)),
                ('status', models.CharField(choices=[('INITIATED', 'Initiated'), ('PENDING', 'Pending'), ('SUCCESS', 'Success'), ('FAILED', 'Failed')], default='INITIATED', max_length=30)),
                ('failure_reason', models.TextField(blank=True, default='')),
                ('idempotency_key', models.CharField(blank=True, max_length=100, null=True, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('paid_at', models.DateTimeField(blank=True, null=True)),
                ('installment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transactions', to='bookings.installment')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='bookings.order')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AlterUniqueTogether(
            name='installment',
            unique_together={('order', 'installment_number')},
        ),
    ]
