# Generated by Django 6.1.1 on 2026-09-15 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0002_installment_alter_booking_consultation_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='installment_plan_snapshot',
            field=models.JSONField(blank=True, default=dict, help_text='Snapshot of the chosen installment plan schedule'),
        ),
        migrations.AddField(
            model_name='order',
            name='next_due_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='payment_type',
            field=models.CharField(choices=[('FULL', 'Full Payment'), ('INSTALLMENT', 'Installment Payment')], default='FULL', max_length=20),
        ),
        migrations.AddField(
            model_name='order',
            name='plan_name',
            field=models.CharField(blank=True, default='Full Payment', max_length=120),
        ),
        migrations.AlterField(
            model_name='order',
            name='payment_plan',
            field=models.CharField(choices=[('FULL_PAYMENT', 'Full Payment'), ('THREE_INSTALLMENTS', 'Three Installments')], default='FULL_PAYMENT', max_length=50),
        ),
    ]
