# Generated by Django 6.1.1 on 2026-09-16 12:38

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0003_order_installment_plan_snapshot_order_next_due_date_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='fulfillment_status',
            field=models.CharField(choices=[('CONFIRMED', 'Confirmed'), ('IN_PRODUCTION', 'In Production'), ('SHIPPED', 'Shipped'), ('OUT_FOR_DELIVERY', 'Out for Delivery'), ('DELIVERED', 'Delivered')], db_index=True, default='CONFIRMED', max_length=30),
        ),
        migrations.AddField(
            model_name='order',
            name='payment_status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('PROCESSING', 'Processing'), ('PARTIALLY_PAID', 'Partially Paid'), ('FULLY_PAID', 'Fully Paid'), ('FAILED', 'Failed'), ('REFUNDED', 'Refunded')], db_index=True, default='PENDING', max_length=30),
        ),
        migrations.AddField(
            model_name='order',
            name='refunded_amount',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12),
        ),
        migrations.CreateModel(
            name='OrderAdminAuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('MANUAL_PAYMENT_ADDED', 'Manual Payment Added'), ('MANUAL_PAYMENT_VERIFIED', 'Manual Payment Verified'), ('MANUAL_PAYMENT_REJECTED', 'Manual Payment Rejected'), ('PAYMENT_ADJUSTMENT', 'Payment Adjustment'), ('REFUND_RECORDED', 'Refund Recorded'), ('WORKSHOP_STATUS_CHANGED', 'Workshop Status Changed'), ('ADMIN_OVERRIDE', 'Admin Override'), ('INSTALLMENT_RESCHEDULED', 'Installment Rescheduled')], max_length=50)),
                ('old_value', models.CharField(blank=True, default='', max_length=255)),
                ('new_value', models.CharField(blank=True, default='', max_length=255)),
                ('amount', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('notes', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='admin_audit_logs', to='bookings.order')),
                ('performed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='order_audit_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Order Admin Audit Log',
                'verbose_name_plural': 'Order Admin Audit Logs',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='OrderStatusHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('previous_status', models.CharField(blank=True, default='', max_length=40)),
                ('fulfillment_status', models.CharField(choices=[('CONFIRMED', 'Confirmed'), ('IN_PRODUCTION', 'In Production'), ('SHIPPED', 'Shipped'), ('OUT_FOR_DELIVERY', 'Out for Delivery'), ('DELIVERED', 'Delivered')], max_length=40)),
                ('admin_notes', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('changed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='workshop_status_changes', to=settings.AUTH_USER_MODEL)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='status_history', to='bookings.order')),
            ],
            options={
                'verbose_name': 'Order Status History',
                'verbose_name_plural': 'Order Status Histories',
                'ordering': ['-created_at'],
            },
        ),
    ]
