# Generated by Django 6.1.1 on 2026-09-19 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0005_backfill_order_statuses'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='fulfillment_status',
            field=models.CharField(choices=[('CONFIRMED', 'CONFIRMED'), ('IN_PRODUCTION', 'IN_PRODUCTION'), ('SHIPPED', 'SHIPPED'), ('OUT_FOR_DELIVERY', 'OUT_FOR_DELIVERY'), ('DELIVERED', 'DELIVERED')], db_index=True, default='CONFIRMED', max_length=30),
        ),
        migrations.AlterField(
            model_name='orderstatushistory',
            name='fulfillment_status',
            field=models.CharField(choices=[('CONFIRMED', 'CONFIRMED'), ('IN_PRODUCTION', 'IN_PRODUCTION'), ('SHIPPED', 'SHIPPED'), ('OUT_FOR_DELIVERY', 'OUT_FOR_DELIVERY'), ('DELIVERED', 'DELIVERED')], max_length=40),
        ),
    ]
