# Generated by Django 6.1.1 on 2026-09-20 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0006_alter_order_fulfillment_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='custom_measurements',
            field=models.CharField(blank=True, default='', help_text='Custom product measurements provided by customer (Length x Width x Height)', max_length=255),
        ),
    ]
