# Generated by Django 6.1.1 on 2026-09-07 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CustomRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('request_id', models.CharField(blank=True, max_length=50, unique=True)),
                ('customer_name', models.CharField(max_length=150)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=25)),
                ('category', models.CharField(default='Custom Living / Dining Piece', max_length=120)),
                ('wood_type', models.CharField(default='Pure Grade-A Burma Teak', max_length=120)),
                ('dimensions', models.CharField(blank=True, default='', max_length=200)),
                ('budget_range', models.CharField(default='₹50,000 - ₹1,00,000', max_length=100)),
                ('description', models.TextField(blank=True, default='')),
                ('reference_image', models.CharField(blank=True, default='', max_length=500)),
                ('status', models.CharField(choices=[('Submitted', 'Submitted'), ('Estimation In Progress', 'Estimation In Progress'), ('Quote Sent', 'Quote Sent'), ('Approved', 'Approved'), ('Crafting Started', 'Crafting Started'), ('Delivered', 'Delivered')], default='Submitted', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
